"""empty message

Revision ID: 3bcbcde7afad
Revises: 820fe288e688
Create Date: 2017-05-19 11:56:54.072373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcbcde7afad'
down_revision = '820fe288e688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('bridgeuser_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bridgeuser_id'], ['bridge_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('bridge_user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge_user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('bridge_user_profile')
    # ### end Alembic commands ###
