"""empty message

Revision ID: 4aeb77285e4b
Revises: 
Create Date: 2017-05-10 23:06:14.378453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeb77285e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(), nullable=True),
    sa.Column('course_ss_id', sa.String(), nullable=True),
    sa.Column('course_socr_id', sa.String(), nullable=True),
    sa.Column('course_moodle_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_map')
    # ### end Alembic commands ###
