"""empty message

Revision ID: 820fe288e688
Revises: eac5b1ea1795
Create Date: 2017-05-19 10:40:11.089934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '820fe288e688'
down_revision = 'eac5b1ea1795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moodle_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('moodle_id', sa.String(), nullable=True),
    sa.Column('moodle_url', sa.String(), nullable=True),
    sa.Column('bridgeuser_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bridgeuser_id'], ['bridge_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ss_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('submitted', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('bridgeuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bridgeuser_id'], ['bridge_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ss_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ss_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interest', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('submitted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ss_user_pkey')
    )
    op.drop_table('ss_transaction')
    op.drop_table('moodle_user')
    op.drop_table('bridge_user')
    # ### end Alembic commands ###
