"""empty message

Revision ID: d783290accf9
Revises: 74cec6ba29bf
Create Date: 2017-05-16 16:02:53.303576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd783290accf9'
down_revision = '74cec6ba29bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ss_user', 'submitted')
    op.drop_column('ss_user', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ss_user', sa.Column('created', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('ss_user', sa.Column('submitted', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
