"""empty message

Revision ID: eac5b1ea1795
Revises: cb28efd08462
Create Date: 2017-05-16 16:07:40.240205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac5b1ea1795'
down_revision = 'cb28efd08462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ss_user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ss_user', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
